//
//  XMLFileDestination.swift
//  Slogger
//
//  Created by David Goodine on 11/7/15.
//  Copyright © 2015 David Goodine. All rights reserved.
//

import Foundation

/// Destination for XML file output.
open class XMLFileDestination: TextFileDestination {

  /// Configuration instance.
  open class XMLConfiguration: Configuration {

    /// Designated initializer.
    public init (generator: Generator = XMLGenerator()) {
      super.init(generator: generator)
      self.fileExtension = "xml"
      self.entryDelimiter = "\n"
      self.fileWrapperGenerator = { (isPreamble) in
        if isPreamble {
          return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\" ?>\n"
            + "<!-- File generated by Slogger: \"http://dgoodine.github.io/Slogger/\" -->\n"
            + "<log>\n"
        } else {
          return "\n</log>\n"
        }
      }
    }
  }

  /// Designated initializer.
  public init(directory: String, config: XMLConfiguration = XMLConfiguration()) {
    super.init(directory: directory, config: config)
  }
}

/// XML log entry generator.
open class XMLGenerator: Generator {

  override func emitBegin(_ outputString: NSMutableString) {
    outputString.append("<entry>")
  }

  override func emit (_ outputString: NSMutableString, type: ValueType) {

    switch type {

    case .boolValue (let detail, let value):
      outputString.append("<\(detail)>\(value)</\(detail)>")

    case .intValue (let detail, let value):
      outputString.append("<\(detail)>\(value)</\(detail)>")

    case .stringValue(let detail, let value, let protect):
      let str = protect ? "<![CDATA[\(value)]]>" : value
      outputString.append("<\(detail)>\(str)</\(detail)>")

    case .dateValue(let detail, let value):
      let ds = dateFormatter.string(from: value)
      outputString.append("<\(detail)>\(ds)</\(detail)>")
    }
  }

  override func emitDelimiter(_ outputString: NSMutableString) {
    outputString.append("")
  }

  override func emitEnd(_ outputString: NSMutableString) {
    outputString.append("</entry>")
  }

}
